name: "Upload Website to S3 bucket"

on:
  push:
    branches: [ main ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3

    - run: npm ci

    - run: npm run generate

    - name: Copy /dist to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.S3_REGION }}
        AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        SOURCE_DIR: 'dist'